//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.NutritionInfo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NutritionInfo.ICalorieCounter")]
    public interface ICalorieCounter {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalorieCounter/GetCalories", ReplyAction="http://tempuri.org/ICalorieCounter/GetCaloriesResponse")]
        string GetCalories(string recipe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalorieCounter/GetCalories", ReplyAction="http://tempuri.org/ICalorieCounter/GetCaloriesResponse")]
        System.Threading.Tasks.Task<string> GetCaloriesAsync(string recipe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalorieCounter/GetNutrients", ReplyAction="http://tempuri.org/ICalorieCounter/GetNutrientsResponse")]
        string GetNutrients(string recipe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalorieCounter/GetNutrients", ReplyAction="http://tempuri.org/ICalorieCounter/GetNutrientsResponse")]
        System.Threading.Tasks.Task<string> GetNutrientsAsync(string recipe);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalorieCounterChannel : FinalProject.NutritionInfo.ICalorieCounter, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalorieCounterClient : System.ServiceModel.ClientBase<FinalProject.NutritionInfo.ICalorieCounter>, FinalProject.NutritionInfo.ICalorieCounter {
        
        public CalorieCounterClient() {
        }
        
        public CalorieCounterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalorieCounterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalorieCounterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalorieCounterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetCalories(string recipe) {
            return base.Channel.GetCalories(recipe);
        }
        
        public System.Threading.Tasks.Task<string> GetCaloriesAsync(string recipe) {
            return base.Channel.GetCaloriesAsync(recipe);
        }
        
        public string GetNutrients(string recipe) {
            return base.Channel.GetNutrients(recipe);
        }
        
        public System.Threading.Tasks.Task<string> GetNutrientsAsync(string recipe) {
            return base.Channel.GetNutrientsAsync(recipe);
        }
    }
}
